#!/usr/bin/env node
/**
 * gen-purge.cjs — writes explicit SQL templates instead of building SQL from
 * nested bash heredocs.
 *
 *   purge-platform.sql   org-4 rows in the shared platform DB
 *   purge-security.sql   the org's own schema in the security DB
 *
 * IMPORTANT: psql does NOT interpolate :variables inside $$ dollar-quoted
 * blocks, so the apply flag is a literal placeholder (__APPLY__) that the runner
 * substitutes with sed, while \if :apply only controls COMMIT vs ROLLBACK.
 */
const fs = require('fs');
const path = require('path');

// Platform tables holding org-4 tenant data.
// Deliberately NOT listed, because the org must still work afterwards:
//   organizations, organization_users, organization_user_devices,
//   organization_roles, organization_control_roles, organization_api_keys,
//   customer_db_connections (needed to reach the security DB),
//   organization_subscriptions, payment_transactions, ai_credit_entries,
//   ai_usage_monthly, ai_settings, tool_subscriptions, client_tool_provisions,
//   branch_review_wallets, organization_alert_settings, alert_channel_targets,
//   business_profiles, compliance_{frameworks,controls,rules,mappings},
//   soc_detection_rules, vapt_procedures, platform_staff, legal_documents,
//   email_templates, platform_tools, schema_migrations.
const PLATFORM = [
  'assets', 'asset_tags', 'asset_tag_assignments', 'asset_history', 'asset_relationships',
  'asset_candidates', 'discovery_jobs',
  'scans', 'scan_jobs', 'scan_work_items', 'scan_results',
  'findings', 'report_finding_tracker', 'report_tracker_history', 'assessment_findings',
  'assessments', 'code_review_findings', 'vapt_correlated_findings', 'verification_evidence',
  'remediation_tasks', 'compliance_evidence', 'reports', 'external_pentest_scopes',
  'risks', 'risk_treatments', 'risk_history', 'risk_assessments',
  'vapt_campaigns', 'vapt_campaign_steps', 'vapt_approval_requests', 'vapt_mining_patterns',
  'vapt_schedules', 'vapt_org_settings',
  'agi_engagements', 'agi_decisions', 'agi_engine_invocations', 'agi_capability_confirmations',
  'agi_engine_capabilities', 'agi_knowledge_docs', 'agi_knowledge_summaries', 'agi_opencode_jobs',
  'agi_skill_outcomes', 'agi_skills', 'agi_tool_install_requests', 'agi_org_agreement_acceptances',
  'agi_org_settings', 'agi_org_context_packs', 'agi_org_test_accounts', 'agi_usage_policies',
  'ai_agent_runs', 'ai_agent_repo_jobs', 'ai_agent_skills', 'ai_agent_approvals',
  'soc_detections', 'soc_cases', 'soc_case_notes',
  'alert_events', 'alert_deliveries', 'notifications',
  'org_application_logs', 'application_logs', 'platform_events', 'audit_events',
  'audit_pending_actions', 'ai_audit_logs', 'server_logs',
  'product_projects', 'product_components', 'product_flows', 'product_documents',
  'product_confirmations', 'product_clarifications', 'threat_clarifications',
  'target_intel_snapshots', 'deployed_agents',
  'integration_installations', 'integration_oauth_states', 'organization_integrations',
  'github_installations', 'github_repositories', 'github_repository_review_settings',
  'scm_credential_targets', 'branch_review_usage_events',
  'compliance_assessments', 'compliance_questionnaire_answers', 'compliance_answerer_sessions',
  'data_subject_requests', 'service_feedback', 'support_tickets', 'support_ticket_messages',
  'funnel_requests', 'access_coupon_redemptions', 'cloud_connectors',
  'launch_sandbox_members', 'launch_sandbox_ratings', 'launch_sandbox_update_receipts',
  'otp_challenges', 'device_confirm_challenges', 'organization_password_resets',
  'organization_user_login_links', 'app_sessions', 'organization_user_sessions',
];

// No organization_id column — these hang off an engagement / session, so they go
// child-first, before agi_engagements itself is deleted.
const CHILDREN = [
  { t: 'agi_transcripts', key: 'session_id', via: 'agi_sessions' },
  { t: 'agi_actions', key: 'session_id', via: 'agi_sessions' },
];

const arr = PLATFORM.map((t) => `'${t}'`).join(', ');

const childBlocks = CHILDREN.map((c) => `  SELECT count(*) INTO n FROM ${c.t} x
    JOIN ${c.via} v ON v.id = x.${c.key}
    JOIN agi_engagements e ON e.id = v.engagement_id
   WHERE e.organization_id = 4;
  total := total + n;
  RAISE NOTICE '  [child] % %', rpad('${c.t}', 34), n;
  IF __APPLY__ AND n > 0 THEN
    DELETE FROM ${c.t} WHERE ${c.key} IN (
      SELECT v.id FROM ${c.via} v JOIN agi_engagements e ON e.id = v.engagement_id
       WHERE e.organization_id = 4);
  END IF;`).join('\n\n');

const HEAD = (what) => `-- generated by gen-purge.cjs — ${what}
\\set ON_ERROR_STOP on
\\set QUIET 0
\\pset pager off
SET client_min_messages TO notice;
\\if :apply
\\echo '*** APPLY ***'
\\else
\\echo '*** PLAN (rolls back) ***'
\\endif
BEGIN;
`;

const platformSql = HEAD('org-4 platform data') + `
DO $$
DECLARE n bigint; total bigint := 0;
BEGIN
${childBlocks}

  -- agi_sessions sits between actions/transcripts and the engagement
  SELECT count(*) INTO n FROM agi_sessions s
    JOIN agi_engagements e ON e.id = s.engagement_id WHERE e.organization_id = 4;
  total := total + n;
  RAISE NOTICE '  [child] % %', rpad('agi_sessions', 34), n;
  IF __APPLY__ AND n > 0 THEN
    DELETE FROM agi_sessions WHERE engagement_id IN (
      SELECT id FROM agi_engagements WHERE organization_id = 4);
  END IF;

  RAISE NOTICE '  [child] subtotal %', total;
END $$;

DO $$
DECLARE t text; n bigint; total bigint := 0;
        tbls text[] := ARRAY[${arr}];
        absent int := 0; noorg int := 0; hit int := 0;
BEGIN
  FOREACH t IN ARRAY tbls LOOP
    IF to_regclass('public.' || quote_ident(t)) IS NULL THEN absent := absent + 1; CONTINUE; END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public' AND table_name = t
                     AND column_name = 'organization_id') THEN
      noorg := noorg + 1;
      RAISE NOTICE '  [skip ] % (no organization_id)', rpad(t, 34);
      CONTINUE;
    END IF;
    EXECUTE format('SELECT count(*) FROM public.%I WHERE organization_id = 4', t) INTO n;
    total := total + n;
    IF n > 0 THEN
      hit := hit + 1;
      RAISE NOTICE '  [rows ] % %', rpad(t, 34), n;
      IF __APPLY__ THEN
        EXECUTE format('DELETE FROM public.%I WHERE organization_id = 4', t);
      END IF;
    END IF;
  END LOOP;
  RAISE NOTICE '  [platform] listed=% absent=% no_org_col=% tables_with_rows=% rows=%',
    array_length(tbls, 1), absent, noorg, hit, total;
END $$;

\\if :apply
COMMIT;
\\else
ROLLBACK;
\\endif
`;

const securitySql = HEAD('org-4 security schema') + `
DO $$
DECLARE t text; n bigint; total bigint := 0; tbls text;
        keep text[] := ARRAY['schema_migrations','soc_detection_rules'];
        ntab int := 0;
BEGIN
  SELECT string_agg(quote_ident(tablename), ', ') INTO tbls
    FROM pg_tables WHERE schemaname = 'phantix' AND NOT (tablename = ANY(keep));
  IF tbls IS NULL THEN RAISE NOTICE '  [security] nothing to clear'; RETURN; END IF;

  FOR t IN SELECT tablename FROM pg_tables
            WHERE schemaname = 'phantix' AND NOT (tablename = ANY(keep)) LOOP
    EXECUTE format('SELECT count(*) FROM phantix.%I', t) INTO n;
    total := total + n; ntab := ntab + 1;
    IF n > 0 THEN RAISE NOTICE '  [rows ] % %', rpad(t, 34), n; END IF;
  END LOOP;
  RAISE NOTICE '  [security] tables=% rows=%', ntab, total;

  IF __APPLY__ THEN
    EXECUTE 'TRUNCATE ' || tbls || ' RESTART IDENTITY CASCADE';
  END IF;
END $$;

\\if :apply
COMMIT;
\\else
ROLLBACK;
\\endif
`;

fs.writeFileSync(path.join(__dirname, 'purge-platform.sql'), platformSql);
fs.writeFileSync(path.join(__dirname, 'purge-security.sql'), securitySql);
console.log(`purge-platform.sql: ${PLATFORM.length} listed + ${CHILDREN.length + 1} child tables, flag=__APPLY__`);
console.log('purge-security.sql: every phantix.* table except schema_migrations, soc_detection_rules');
