-- generated by gen-purge.cjs — org-4 security schema
\set ON_ERROR_STOP on
\set QUIET 0
\pset pager off
SET client_min_messages TO notice;
\if :apply
\echo '*** APPLY ***'
\else
\echo '*** PLAN (rolls back) ***'
\endif
BEGIN;

DO $$
DECLARE t text; n bigint; total bigint := 0; tbls text;
        keep text[] := ARRAY['schema_migrations','soc_detection_rules'];
        ntab int := 0;
BEGIN
  SELECT string_agg(quote_ident(tablename), ', ') INTO tbls
    FROM pg_tables WHERE schemaname = 'phantix' AND NOT (tablename = ANY(keep));
  IF tbls IS NULL THEN RAISE NOTICE '  [security] nothing to clear'; RETURN; END IF;

  FOR t IN SELECT tablename FROM pg_tables
            WHERE schemaname = 'phantix' AND NOT (tablename = ANY(keep)) LOOP
    EXECUTE format('SELECT count(*) FROM phantix.%I', t) INTO n;
    total := total + n; ntab := ntab + 1;
    IF n > 0 THEN RAISE NOTICE '  [rows ] % %', rpad(t, 34), n; END IF;
  END LOOP;
  RAISE NOTICE '  [security] tables=% rows=%', ntab, total;

  IF __APPLY__ THEN
    EXECUTE 'TRUNCATE ' || tbls || ' RESTART IDENTITY CASCADE';
  END IF;
END $$;

\if :apply
COMMIT;
\else
ROLLBACK;
\endif
